### ISSUE TITLE
[Presentation]

### ISSUE THREAD

**Issue by WestarkMFF** [vuejs/events#115] opened 2020-04-23 03:33 UTC
## Presentation

No need to post an issue for a presentation just get the presentation author authorization and submit a pull request following [this format](https://github.com/vuejs/events/compare/master...presnetation-pr-example?template=pull-request-presentation.md)

If you meet a deadlink or a wrong informations please contact the author of the presentation.

**Comment by TheJaredWilcurt** [comment] 2020-04-24 22:58
That link doesn't work, it's the same link on the website

* https://github.com/vuejs/events/compare/master...presentation-pr-example?template=pull-request-presentation.md

![nothing](https://user-images.githubusercontent.com/4629794/80263134-9b12c300-865d-11ea-8767-931d0f28dc09.png)

**Comment by bencodezen** [comment] 2020-04-27 03:26
@WestarkMFF Can you clarify what you are having issues with?

**Comment by kissu** [comment] 2022-06-25 17:00
OP was mentioning [this file](https://github.com/vuejs/events/blob/main/.github/PULL_REQUEST_TEMPLATE/pull-request-presentation.md) apparently.
I'm closing it since the issue is quite old and probably solved already.

Feel free to answer below @WestarkMFF if you feel like your issue is not solved, I'll gladly reopen it. 💚

**Closed by kissu** 2022-06-25 17:00 UTC
